spring:
  datasource:
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  redis:
    host: ${REDIS_USER}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}
  session:
    store-type: redis
  web:
    resources:
      add-mappings: false
  mail:
    properties:
      auth: true
      starttls:
        enable: true
        required: true
      connectiontimeout: 5000
      timeout: 3000
      writetimeout: 5000
    host: ${SMTP_HOST}
    username: ${SMTP_USER}
    password: ${SMTP_PASSWORD}
    port: 587

logging:
  loggly:
    token: ${LOGGLY_TOKEN}

algafood:
  storage:
    tipo: s3
    s3:
      bucket: ${S3_BUCKET}
      regiao: ${S3_REGIAO}
      id-chave-acesso: ${S3_ID_CHAVE_ACESSO}
      diretorio-fotos: ${S3_DIRETORIO_FOTOS}
      chave-acesso-secreta: ${S3_ID_CHAVE_ACESSO_SECRETA}
  email:
    remetente: ${EMAIL_REMETENTE}
    impl: smtp
  jwt:
    keystore:
      jks-location: ${JKS_LOCATION}
      password: ${JKS_PASSWORD}
      keypair-alias: ${JKS_KEYPAIR_ALIAS}

