server:
  compression:
    enabled: true

spring:
  datasource:
    url: ${DATABASE_URL}?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  flyway:
    locations: classpath:db/migration,classpath:db/testdata
  jpa:
    database: MYSQL
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL57Dialect
  jackson:
    deserialization:
      fail-on-unknown-properties: true
      fail-on-ignored-properties: true
  mvc:
    throw-exception-if-no-handler-found: true
    pathmatch.matching-strategy: ANT_PATH_MATCHER
  web:
    resources.add-mappings: false
  freemarker:
    settings:
      locale: pt_BR
  mail:
    properties:
      auth: true
      starttls:
        enable: true
      connectiontimeout: 5000
      timeout: 3000
      writetimeout: 5000
    host: smtp.sendgrid.net
    port: 587
    username: apikey
    password: ${SENDGRID_API_KEY}

algafood:
  storage:
    tipo: s3
    local:
      diretorio-fotos: /home/gabriel/Desktop/catalogo
    s3:
      bucket: ${S3_BUCKET}
      regiao: ${S3_REGIAO}
      id-chave-acesso: ${S3_ID_CHAVE_ACESSO}
      diretorio-fotos: ${S3_DIRETORIO_FOTOS}
      chave-acesso-secreta: ${S3_ID_CHAVE_ACESSO_SECRETA}
  email:
    remetente: Algafood <gabrieltonhatti37@gmail.com>
    impl: sandbox
    sandbox.destinatario: email.teste.aw12@gmail.com

logging:
  loggly:
    token: ${LOGGLY_TOKEN}
#  level:
#    org:
#      springframework: DEBUG
